# Generated by Django 6.0.6 on 2026-06-13 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_day', 'First Day Champion'), ('streak_3', '3-Day Streak'), ('streak_7', 'Weekly Warrior'), ('goal_crusher', 'Goal Crusher'), ('hydration_hero', 'Hydration Hero')], max_length=20)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_goal_ml', models.PositiveIntegerField(default=2000)),
                ('preferred_unit', models.CharField(choices=[('ml', 'Milliliters'), ('oz', 'Fluid Ounces')], default='ml', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='waterintakeentry',
            name='records_wat_date_f3d4fc_idx',
        ),
        migrations.AddField(
            model_name='waterintakeentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='water_intakes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='waterintakeentry',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='waterintakeentry',
            index=models.Index(fields=['user', 'date'], name='records_wat_user_id_b80b76_idx'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together={('user', 'achievement_type')},
        ),
    ]
